train:
  elasticnet:
    alpha: 0.1
    l1_ratio: 0.1
  hgbr:
    learning_rate: 0.13
    max_depth: 43
    max_leaf_nodes: 23
    min_samples_leaf: 20
    l2_regularization: 0.015
  linearsvr:
    epsilon: 0.09
    C: 0.05
  rbf:
    epsilon: 0.03
    C: 7
    gamma: 0.008
  mlpr:
    batch_size: 64
    hidden_layer_sizes: [50]
    learning_rate_init: 0.01